name: CI

on: [push]

jobs:
  test-lint-build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      
    - name: Cache emscripten build
      id: cache-emscripten-build
      uses: actions/cache@v1
      with:
        path: 'packages/epanet-engine/dist'
        key: emscrip-${{ hashFiles('packages/epanet-engine/src/**')}}-${{ hashFiles('packages/epanet-engine/Dockerfile')}}-${{ hashFiles('packages/epanet-engine/build.sh')}}

    - name: list files
      run: ls -LR  packages/epanet-engine
    - name: Build emscripten docker container
      if: steps.cache-emscripten-build.outputs.cache-hit != 'true'
      run: yarn build:docker
    - name: Compile OWA-EPANET to JS
      if: steps.cache-emscripten-build.outputs.cache-hit != 'true'
      run:  yarn build:engine
    - uses: actions/checkout@v1
    - name: Use Yarn Cache
      uses: actions/cache@v1
      with:
        path: ~/.cache/yarn
        key: yarn-${{ hashFiles( '/yarn.lock') }}
    - name: Install Dependencies
      run: yarn install
    - name: Running tests
      run: yarn test
    - name: Running linter
      run: yarn lint
    - name: Running build
      run: yarn build

